//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlTableDiff.Defaults {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Tables : global::System.Configuration.ApplicationSettingsBase {
        
        private static Tables defaultInstance = ((Tables)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Tables())));
        
        public static Tables Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CCS_Default, CCS_Default_Group")]
        public string DefaultList {
            get {
                return ((string)(this["DefaultList"]));
            }
        }
    }
}
